### PR TITLE
[Requirements] Update

### PR DESCRIPTION
**Pull request by Herklos**
Depends on https://github.com/Drakkar-Software/OctoBot-Websockets/pull/20

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
will be fixed after the next octobot_backtesting release containing: https://github.com/Drakkar-Software/OctoBot-Backtesting/pull/29

**Comment by GuillaumeDSM** [comment]
We should close this PR

**Comment by Herklos** [comment]
> We should close this PR

Why ?

**Comment by GuillaumeDSM** [comment]
> > We should close this PR
> 
> Why ?

My bad, I thought it was only about the previous backtesting import error, it's not

**Pull request merged**
