### PR TITLE
WIP add RunAnalysis Mode and evaluators

### PR DESCRIPTION
**Pull request by techfreaque**

### CODE REVIEW

**Comment by GuillaumeDSM** [comment]
is this a WIP ?

**Comment by techfreaque** [comment]
> 

Yes its WIP, this is the part where the RunAnalysis factory needs to be implemented

**Comment by GuillaumeDSM** [comment]
> > 
> 
> Yes its WIP, this is the part where the RunAnalysis factory needs to be implemented

Ok so here WIP doesn't mean that you are not done with the PR but rather that there is some work left to be done after merging ?

**Comment by techfreaque** [comment]
> > > 
> > 
> > 
> > Yes its WIP, this is the part where the RunAnalysis factory needs to be implemented
> 
> Ok so here WIP doesn't mean that you are not done with the PR but rather that there is some work left to be done after merging ?

Its up to you if you wanna merge it before the RunAnalysis factory is done.
This PR is intended to be just a place to discuss the topic and share my first draft

**Comment by techfreaque** [comment]
closed as this code is outdated

**Pull request closed without merging**
